area_name = [
    "Bagnotar"
    "Bakote"
    "Dhamtour"
    "Hajia gali"
    "Havelian village"
    "Jhangi"
    "Kakul"
    "Kunj"
    "Lora"
    "Mirpur"
    "Pind Kargu khan"
    "Sajikot"
    "Salhad"
    "Sheikh ul bandi"
    "Sherwan"
    "Samunder katha"
    "Havelian"
    "Malik pura"
    "Nawanshehr"
    "Rajoya"
    "Malkot"
    "Qalabdarabaad"
    "Batala"
    "Bandi Attai khan"
    "Kuthiala"
    "Halmaira"
    "Bagan"
    "Bagh"
    "Banda pir khan"
    "Bandi Dhundan"
    "Bodla"
    "Boi"
    "Bhuraj"
    "Chamhad"
    "Chamhatti"
    "Chamiali"
    "Maira"
    "Dalola"
    "Garhi noor pur"
    "Ghambir"
    "Ghora bazgran"
    "Hadora"
    "Harno aziz abad"
    "Jarral"
    "Jhangra"
    "Kanthiyali"
    "Khaira gali"
    "Muslimabad"
    "Mandiyan"
    "Kaala pull"
    "Supply"
    "Cantt"
    "Bilal town"
    "Phalkot"
    "Link road"
    "Chinnar road"
    "Neelay pair"
    "Mansehra road"
    "Jinnahabad"
    "Kalabagh"
    "Noorpur"
    "Aliabad"
    "Phullan"
    "Jabrian"
    "Shimla"
    "Sultanpur"
    "Birote"
    "Choona kari"
    "Karim pura"
    "Jhafar"
    "Langrial"
    "Malkan"
    "Industry road"
    "College road"
    "Sarban chowck"
    "Fawara chowck"
    "Ghora chowck"
    "Missile chowck"
    "Lodhiabad"
    "Upper kehal"
    "Murre road"
    "PMA road"
    "Javed shaheed road"
    "Habibullah colony"
    "Kaghan colony"
]
